name: Main

on:
  push:
  schedule:
    - cron: '0 8 * * 2'

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  publish:
    if: github.ref_name == 'main'
    needs: build
    uses: ./.github/workflows/publish.yaml
